import type { CollectionEntry } from "astro:content";
import { getCollection } from "astro:content";
import type { Lang } from "../i18n/config";

type BlogPost = CollectionEntry<"blog">;

/**
 * Extract base slug from a post id generated by our custom generateId.
 * The id format is "{base-slug}/{lang}", e.g. "calculus-fundamentals/en".
 *
 * "calculus-fundamentals/en" → "calculus-fundamentals"
 * "physics-basic-marginalia/zh" → "physics-basic-marginalia"
 */
export function getBaseSlug(postId: string): string {
  const lastSlash = postId.lastIndexOf("/");
  if (lastSlash === -1) return postId;
  return postId.slice(0, lastSlash);
}

/**
 * Extract language from a post id.
 * "calculus-fundamentals/en" → "en"
 */
export function getLangFromPostId(postId: string): Lang {
  const lastSlash = postId.lastIndexOf("/");
  if (lastSlash === -1) return "en";
  const suffix = postId.slice(lastSlash + 1);
  if (suffix === "zh" || suffix === "en") return suffix;
  return "en";
}

/**
 * Get all non-draft posts for a specific language.
 */
export async function getPostsByLang(lang: Lang): Promise<BlogPost[]> {
  const all = await getCollection("blog", ({ data }) => !data.draft);
  return all.filter((post) => getLangFromPostId(post.id) === lang);
}

/**
 * Build a Map<baseSlug, Map<lang, BlogPost>> for translation pairing.
 * Used by the article detail page to determine if a translation exists.
 */
export async function buildTranslationMap(): Promise<
  Map<string, Map<Lang, BlogPost>>
> {
  const all = await getCollection("blog", ({ data }) => !data.draft);
  const map = new Map<string, Map<Lang, BlogPost>>();
  for (const post of all) {
    const base = getBaseSlug(post.id);
    const lang = getLangFromPostId(post.id);
    if (!map.has(base)) map.set(base, new Map());
    map.get(base)!.set(lang, post);
  }
  return map;
}

/**
 * Check if a translation exists for a given post.
 * Returns the other-language post or null.
 */
export function findTranslation(
  post: BlogPost,
  translationMap: Map<string, Map<Lang, BlogPost>>,
): BlogPost | null {
  const base = getBaseSlug(post.id);
  const currentLang = getLangFromPostId(post.id);
  const otherLang: Lang = currentLang === "zh" ? "en" : "zh";
  return translationMap.get(base)?.get(otherLang) ?? null;
}
